/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esante;

import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ixlam
 */
public class CalenderCell extends javax.swing.JPanel implements TableCellRenderer {
    
    /**
     * Creates new form CalanderCell
     * @param value
     */
    Reservation res;
    boolean old;
    Date date;
    CalenderTable container;
    
    public boolean isReserved() {
        return res != null && !res.getType().equals("VISITE");
    }
    
    public boolean isFinished() {
        return res != null && res.getType().equals("VISITE");
    }
    
    public Reservation getReservation() {
        return res;
    }
    
    public void setInfo(String info) {
        jLabel2.setText(info);
    }
    
    public CalenderCell(CalenderTable container, String value, Date date, boolean old, Reservation res) {
        this.date = date;
        this.res = res;
        initComponents();
        jLabel1.setText(value);
        setBackground(new Color(0, 0, 0, 0));
        if (old) {
            setBackground(new Color(0, 0, 0, 10));
            jLabel1.setForeground(new Color(100, 100, 100));
        }
        if (isReserved()) {
            setBackground(new Color(255, 0, 0, 50));
        }
        if (isFinished()) {
            setBackground(new Color(255, 255, 0, 50));
        }
        this.old = old;
        this.container = container;
    }
    
    public Date getDate() {
        return date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout(5, 5));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel2.setText(" ");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("0");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
        if (bln && !old) {
            setBackground(new Color(0, 255, 0, 50));
            if (isReserved())
                setBackground(new Color(255, 0, 0, 80));
        }
        return this;
    }

}
