/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esante;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ixlam
 */
public class Calender extends javax.swing.JPanel {

    /**
     * Creates new form Calander
     */
    HashMap<String, Reservation> reserved;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
    
    java.util.Calendar c;
    String[] months = new String[] {
        "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"
    };
    
    ArrayList<CalenderEvent> ce = new ArrayList<>();
    
    public void addOnCalenderEvent(CalenderEvent e) {
        ce.add(e);
    }
    
    public void clearReserved() {
        reserved.clear();
        updateCalender();
    }
    
    public void addReservedDate(Date date, Reservation res) {
        reserved.putIfAbsent(sdf.format(date), res);
    }
    
    public void removeReservedDate(Date date) {
        if (reserved.containsKey(sdf.format(date))) reserved.remove(sdf.format(date));
    }
    
    public boolean isReserved(Date date) {
        return reserved.containsKey(sdf.format(date));
    }
    
    public Reservation getReservation(Date date) {
        return reserved.get(sdf.format(date));
    }
    
    public Calender() {
        reserved = new HashMap<>();
        initComponents();
        calanderTable1.setCalender(this);
        
        c = java.util.Calendar.getInstance();
        moveMonth(0);
        ListSelectionModel rowSelectionModel = calanderTable1.getSelectionModel();
        ListSelectionModel columnSelectionModel = calanderTable1.getColumnModel().getSelectionModel();

        ListSelectionListener selectionListener = new ListSelectionListener() {

            int lsr = -1;
            int lsc = -1;
            
            public void valueChanged(ListSelectionEvent e) {
               if((e.getSource() == rowSelectionModel || e.getSource() == columnSelectionModel) && !e.getValueIsAdjusting()) {
                   int row = calanderTable1.getSelectedRow();
                   int col = calanderTable1.getSelectedColumn();
                   if(lsr != row || lsc != col) {
                       CalenderCell cell = (CalenderCell)calanderTable1.getCellRenderer(row, col);
                       for(CalenderEvent ev: ce) {
                           ev.OnCellSelected(cell);
                       }
           
                   }
                   lsr = row;
                   lsc = col;
               }
            }
        };

        rowSelectionModel.addListSelectionListener(selectionListener);
        columnSelectionModel.addListSelectionListener(selectionListener);


        
    }
    
    void moveMonth(int dir) {
        c.add(java.util.Calendar.MONTH, dir);
        updateCalender();
    }
    
    void updateCalender() {
        calanderTable1.updateCalendar(c);
        jLabel1.setText(months[c.get(java.util.Calendar.MONTH)] + " - " + c.get(java.util.Calendar.YEAR));
        calanderTable1.clearSelection();
        updateUI();
    }
    
    int rowOfDate(Date date) {
        java.util.Calendar now = java.util.Calendar.getInstance();
        now.set(date.getYear(), date.getMonth(), 1, 0, 0, 0);
        int fday = now.get(java.util.Calendar.DAY_OF_WEEK) + 1;
        int row = (date.getDate() + fday) / 7;
        return row;
    }
    
    int columnOfDate(Date date ) {
        java.util.Calendar now = java.util.Calendar.getInstance();
        now.set(date.getYear(), date.getMonth(), 1, 0, 0, 0);
        int fday = now.get(java.util.Calendar.DAY_OF_WEEK) + 1;
        int col = (date.getDate() + fday) % 7;
        return col;
    }
    
    public void setDate(Date date) {
        c.setTime(date);
        updateCalender();
        int row = rowOfDate(date);
        int col = columnOfDate(date);
        calanderTable1.setRowSelectionInterval(row, row);
        calanderTable1.setColumnSelectionInterval(col, col);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        calanderTable1 = new esante.CalenderTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 246, 249));

        calanderTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        calanderTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calanderTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(calanderTable1);

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(">");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Janvier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        moveMonth(1);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        moveMonth(-1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void calanderTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calanderTable1MouseClicked
        
    }//GEN-LAST:event_calanderTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private esante.CalenderTable calanderTable1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
