/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package esante;

import java.awt.Frame;

/**
 *
 * @author ixlam
 */
public class loginPopup extends javax.swing.JDialog {

    /**
     * Creates new form loginPopup
     */
    
    String pswd;
    
    public loginPopup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pswd = "";
        initComponents();
        ComponentMover cm = new ComponentMover(getClass(), jPanel2);
        setLocationRelativeTo(null);
    }
    
    static String show(Frame parent, String username) {
        loginPopup lpp = new loginPopup(parent, true);
        lpp.lptfUsername.setText(username);
        lpp.setVisible(true);
        return lpp.pswd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lpLabelUsername = new javax.swing.JLabel();
        lptfUsername = new javax.swing.JTextField();
        lpLabelPassword = new javax.swing.JLabel();
        lppfPassword = new javax.swing.JPasswordField();
        lpBtnAnuller = new javax.swing.JButton();
        lpBtnConnecter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(57, 72, 103));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lpLabelUsername.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lpLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        lpLabelUsername.setText("Utilisateur:");

        lptfUsername.setEditable(false);
        lptfUsername.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lptfUsername.setForeground(new java.awt.Color(51, 51, 51));
        lptfUsername.setText("admin");
        lptfUsername.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        lptfUsername.setEnabled(false);
        lptfUsername.setFocusable(false);

        lpLabelPassword.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lpLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        lpLabelPassword.setText("Mot de passe :");

        lppfPassword.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lppfPassword.setForeground(new java.awt.Color(51, 51, 51));
        lppfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lppfPasswordActionPerformed(evt);
            }
        });

        lpBtnAnuller.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lpBtnAnuller.setForeground(new java.awt.Color(51, 51, 51));
        lpBtnAnuller.setText("Anuller");
        lpBtnAnuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpBtnAnullerActionPerformed(evt);
            }
        });

        lpBtnConnecter.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lpBtnConnecter.setForeground(new java.awt.Color(51, 51, 51));
        lpBtnConnecter.setText("Connecter");
        lpBtnConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpBtnConnecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lpBtnAnuller, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lpBtnConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lpLabelPassword)
                            .addComponent(lpLabelUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lppfPassword)
                            .addComponent(lptfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpLabelUsername)
                    .addComponent(lptfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lppfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpBtnConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpBtnAnuller, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lppfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lppfPasswordActionPerformed
        pswd = lppfPassword.getText();
        setVisible(false);
    }//GEN-LAST:event_lppfPasswordActionPerformed

    private void lpBtnAnullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpBtnAnullerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_lpBtnAnullerActionPerformed

    private void lpBtnConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpBtnConnecterActionPerformed
        pswd = lppfPassword.getText();
        setVisible(false);
    }//GEN-LAST:event_lpBtnConnecterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lpBtnAnuller;
    private javax.swing.JButton lpBtnConnecter;
    private javax.swing.JLabel lpLabelPassword;
    private javax.swing.JLabel lpLabelUsername;
    private javax.swing.JPasswordField lppfPassword;
    private javax.swing.JTextField lptfUsername;
    // End of variables declaration//GEN-END:variables
}
