/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package esante;

/**
 *
 * @author islam
 */
public class Searchbar extends javax.swing.JPanel {

    /**
     * Creates new form Searchbar
     */
    public Searchbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel31 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esante/icons8-search-24.png"))); // NOI18N
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel31.setIconTextGap(8);
        jLabel31.setMaximumSize(new java.awt.Dimension(999, 999));
        jLabel31.setPreferredSize(new java.awt.Dimension(999, 999));
        jLabel31.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 42));

        search.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        search.setForeground(new java.awt.Color(51, 51, 51));
        search.setMargin(new java.awt.Insets(2, 40, 2, 6));
        search.setPreferredSize(getPreferredSize());
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 359, 42));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel31;
    public javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
